apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
    - name: "8443"
      port: 8443
      protocol: TCP
      targetPort: {{ .Values.service.containerPort }}
  selector:
    app: {{ .Values.service.name }}